service:
  name: voto-limpo-authentication

frameworkVersion: '2'

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  s3Sync:
    - bucketName: voto-limpo-bucket
      localDir: build

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 19
  region: eu-west-2
  apiGateway:
    minimumCompressionSize: 1024
  environment: 1


# Functions

functions:
  signin:
    handler: handler.signin
  callback:
    handler: handler.callback
  refresh:
    handler: handler.refresh
  authorize:
    handler: handler.authorize
