service:
  name: voto-limpo-authentication

frameworkVersion: '2'

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  secrets: ${ssm:/aws/reference/secretsmanager/voto-limpo/dev~true}

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 19
  region: eu-west-2
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    GOOGLE_CLIENT_ID: ${self:custom.secrets.GOOGLE_CLIENT_ID}
    GOOGLE_CLIENT_SECRET_KEY: ${self:custom.secrets.GOOGLE_CLIENT_SECRET_KEY}
    BASE_URL: ${self:custom.secrets.BASE_URL}


# Functions

functions:
  signin:
    handler: src/functions/signin.handler
    events:
      - http:
          path: login
          method: get

  callback:
    handler: src/functions/callback.handler
    events:
      - http:
          path: callback
          method: get
  # refresh:
  #   handler: refresh
  # authorize:
  #   handler: authorize
